%function [t1,temperature1,c1,varunkown,s,salinity,VarName7,t2,temperature2,lat,latMinutes,latDegrees,latDirection,lon,lonMinutes,lonDegrees,lonDirection,hms,TimeHHMMSS,dmy,DateDDMMYY] = importfile1(filename, startRow, endRow)
function [TemperatureBoat, TemperatureInstr, Salinity, LatDegrees, LatMinutes, LatSign, LonDegrees, LonMinutes, LonSign, Time1, Date1] = importfileTSG(filename, startRow, endRow);

%IMPORTTSG2 Import numeric data from a text file as column vectors.
%   [TEMPERATUREBOAT, TEMPERATUREINSTR, SALINITY, LATMINUTES, LATDEGREES, LATSIGN, LONMINUTES, LONDEGREES, LONSIGN, TIME1, DATE1]
%   = IMPORTTSG3(FILENAME) Reads data from text file FILENAME for the
%   default selection.
%
%   [TEMPERATUREBOAT, TEMPERATUREINSTR, SALINITY, LATMINUTES, LATDEGREES, LATSIGN, LONMINUTES, LONDEGREES, LONSIGN, TIME1, DATE1]
%   = IMPORTTSG3(FILENAME, STARTROW, ENDROW) Reads data from rows STARTROW
%   through ENDROW of text file FILENAME.
%
% Example:
%   []
%   = importTSG3('tara_tsg_20140624.txt',1, 2198);
%
%    See also TEXTSCAN.

% Auto-generated by MATLAB on 2015/05/05 08:35:06
% Changed to reverse degrees/minutes 2015/05/27
% Changed to separate two temperatures into TemperatureBoat and
% TemperatureInstr 2015/05/27

%% Initialize variables.
if nargin<=2
    startRow = 1;
    endRow = inf;
end

%% Read columns of data as strings:
% For more information, see the TEXTSCAN documentation.
formatSpec = 't1=%f, c1=%f, s=%f, t2=%f, lat=%u %f %c, lon=%u %f %c, hms=%6s, dmy=%6s';

%% Open the text file.
fileID = fopen(filename,'r');

%% Read columns of data according to format string.
% This call is based on the structure of the file used to generate this
% code. If an error occurs for a different file, try regenerating the code
% from the Import Tool.
dataArray = textscan(fileID, formatSpec, endRow(1)-startRow(1)+1, 'EmptyValue', NaN, 'ReturnOnError', false);

for block=2:length(startRow)
    frewind(fileID);
    
    %dataArrayBlock = textscan(fileID, formatSpec, endRow(block)-startRow(block)+1, 'Delimiter', '', 'WhiteSpace', '', 'HeaderLines', startRow(block)-1, 'ReturnOnError', false);
    dataArray = textscan(fileID, formatSpec, endRow(1)-startRow(1)+1, 'ReturnOnError', false);
    for col=1:length(dataArray)
        dataArray{col} = [dataArray{col};dataArrayBlock{col}];
    end
end

%% Close the text file.
fclose(fileID);

%% Post processing for unimportable data.
% No unimportable data rules were applied during the import, so no post
% processing code is included. To generate code which works for
% unimportable data, select unimportable cells in a file and regenerate the
% script.

%% Allocate imported array to column variable names
TemperatureInstr = dataArray{1};
TemperatureBoat = dataArray{4};
Salinity = dataArray{3};
LatDegrees = double(dataArray{5});
LatMinutes = dataArray{6};
LatSign = dataArray{7};
LonDegrees = double(dataArray{8});
LonMinutes = dataArray{9};
LonSign = dataArray{10};
Date1 = dataArray{12};
Time1 = dataArray{11};

end

