function [year1,dec_yearday,lat,lon,gq,svc,hdop,altitude] = importfileSEATEX(filename, startRow, endRow)
%IMPORTFILE1 Import numeric data from a text file as column vectors.
%   [YEAR1,DEC_YEARDAY,LAT,LON,GQ,SVC,HDOP,ALTITUDE] =
%   IMPORTFILE1(FILENAME) Reads data from text file FILENAME for the
%   default selection.
%
%   [YEAR1,DEC_YEARDAY,LAT,LON,GQ,SVC,HDOP,ALTITUDE] =
%   IMPORTFILE1(FILENAME, STARTROW, ENDROW) Reads data from rows STARTROW
%   through ENDROW of text file FILENAME.
%
% Example:
%   [year1,dec_yearday,lat,lon,gq,svc,hdop,altitude] = importfile1('seatex-gga.299',1, 44616);
%
%    See also TEXTSCAN.

% Auto-generated by MATLAB on 2016/09/14 11:13:04

%% Initialize variables.
delimiter = ',';
if nargin<=2
    startRow = 1;
    endRow = inf;
end

%% Format string for each line of text:
%   column1: double (%f)
%	column2: double (%f)
%   column6: double (%f)
%	column7: double (%f)
%   column8: double (%f)
%	column9: double (%f)
%   column10: double (%f)
%	column11: double (%f)
% For more information, see the TEXTSCAN documentation.
formatSpec = '%f%f%*s%*s%*s%f%f%f%f%f%f%*s%*s%[^\n\r]';

%% Open the text file.
fileID = fopen(filename,'r');

%% Read columns of data according to format string.
% This call is based on the structure of the file used to generate this
% code. If an error occurs for a different file, try regenerating the code
% from the Import Tool.
dataArray = textscan(fileID, formatSpec, endRow(1)-startRow(1)+1, 'Delimiter', delimiter, 'EmptyValue' ,NaN,'HeaderLines', startRow(1)-1, 'ReturnOnError', false);
for block=2:length(startRow)
    frewind(fileID);
    dataArrayBlock = textscan(fileID, formatSpec, endRow(block)-startRow(block)+1, 'Delimiter', delimiter, 'EmptyValue' ,NaN,'HeaderLines', startRow(block)-1, 'ReturnOnError', false);
    for col=1:length(dataArray)
        dataArray{col} = [dataArray{col};dataArrayBlock{col}];
    end
end

%% Close the text file.
fclose(fileID);

%% Post processing for unimportable data.
% No unimportable data rules were applied during the import, so no post
% processing code is included. To generate code which works for
% unimportable data, select unimportable cells in a file and regenerate the
% script.

%% Allocate imported array to column variable names
year1 = dataArray{:, 1};
dec_yearday = dataArray{:, 2};
lat = dataArray{:, 3};
lon = dataArray{:, 4};
gq = dataArray{:, 5};
svc = dataArray{:, 6};
hdop = dataArray{:, 7};
altitude = dataArray{:, 8};


