function [year1,dec_yearday,airtemp1,humidity1,par1,tir1,airtemp2,humidity2,par2,tir2,baro1,baro2,tstemp,conductivity,salinity,sound_velocity,chlorophyll,sampletemp,flowrate,sstemp,trans,sstemp2] = importfileOceanLogger2(filename, startRow, endRow)
%IMPORTFILE1 Import numeric data from a text file as column vectors.
%   [YEAR1,DEC_YEARDAY,AIRTEMP1,HUMIDITY1,PAR1,TIR1,AIRTEMP2,HUMIDITY2,PAR2,TIR2,BARO1,BARO2,TSTEMP,CONDUCTIVITY,SALINITY,SOUND_VELOCITY,CHLOROPHYLL,SAMPLETEMP,FLOWRATE,SSTEMP,TRANS,SSTEMP2]
%   = IMPORTFILE1(FILENAME) Reads data from text file FILENAME for the
%   default selection.
%
%   [YEAR1,DEC_YEARDAY,AIRTEMP1,HUMIDITY1,PAR1,TIR1,AIRTEMP2,HUMIDITY2,PAR2,TIR2,BARO1,BARO2,TSTEMP,CONDUCTIVITY,SALINITY,SOUND_VELOCITY,CHLOROPHYLL,SAMPLETEMP,FLOWRATE,SSTEMP,TRANS,SSTEMP2]
%   = IMPORTFILE1(FILENAME, STARTROW, ENDROW) Reads data from rows STARTROW
%   through ENDROW of text file FILENAME.
%
% Example:
%   [year1,dec_yearday,airtemp1,humidity1,par1,tir1,airtemp2,humidity2,par2,tir2,baro1,baro2,tstemp,conductivity,salinity,sound_velocity,chlorophyll,sampletemp,flowrate,sstemp,trans,sstemp2] = importfile1('oceanlogger.299',1, 10705);
%
%    See also TEXTSCAN.

% Auto-generated by MATLAB on 2016/09/14 13:01:25

%% Initialize variables.
delimiter = ',';
if nargin<=2
    startRow = 1;
    endRow = inf;
end

%% Format string for each line of text:
%   column1: double (%f)
%	column2: double (%f)
%   column6: double (%f)
%	column7: double (%f)
%   column8: double (%f)
%	column9: double (%f)
%   column10: double (%f)
%	column11: double (%f)
%   column12: double (%f)
%	column13: double (%f)
%   column14: double (%f)
%	column15: double (%f)
%   column16: double (%f)
%	column17: double (%f)
%   column18: double (%f)
%	column19: double (%f)
%   column20: double (%f)
%	column21: double (%f)
%   column22: double (%f)
%	column23: double (%f)
%   column24: double (%f)
%	column25: double (%f)
% For more information, see the TEXTSCAN documentation.
formatSpec = '%f%f%*s%*s%*s%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%[^\n\r]';

%% Open the text file.
fileID = fopen(filename,'r');

%% Read columns of data according to format string.
% This call is based on the structure of the file used to generate this
% code. If an error occurs for a different file, try regenerating the code
% from the Import Tool.
dataArray = textscan(fileID, formatSpec, endRow(1)-startRow(1)+1, 'Delimiter', delimiter, 'EmptyValue' ,NaN,'HeaderLines', startRow(1)-1, 'ReturnOnError', false);
for block=2:length(startRow)
    frewind(fileID);
    dataArrayBlock = textscan(fileID, formatSpec, endRow(block)-startRow(block)+1, 'Delimiter', delimiter, 'EmptyValue' ,NaN,'HeaderLines', startRow(block)-1, 'ReturnOnError', false);
    for col=1:length(dataArray)
        dataArray{col} = [dataArray{col};dataArrayBlock{col}];
    end
end

%% Close the text file.
fclose(fileID);

%% Post processing for unimportable data.
% No unimportable data rules were applied during the import, so no post
% processing code is included. To generate code which works for
% unimportable data, select unimportable cells in a file and regenerate the
% script.

%% Allocate imported array to column variable names
year1 = dataArray{:, 1};
dec_yearday = dataArray{:, 2};
airtemp1 = dataArray{:, 3};
humidity1 = dataArray{:, 4};
par1 = dataArray{:, 5};
tir1 = dataArray{:, 6};
airtemp2 = dataArray{:, 7};
humidity2 = dataArray{:, 8};
par2 = dataArray{:, 9};
tir2 = dataArray{:, 10};
baro1 = dataArray{:, 11};
baro2 = dataArray{:, 12};
tstemp = dataArray{:, 13};
conductivity = dataArray{:, 14};
salinity = dataArray{:, 15};
sound_velocity = dataArray{:, 16};
chlorophyll = dataArray{:, 17};
sampletemp = dataArray{:, 18};
flowrate = dataArray{:, 19};
sstemp = dataArray{:, 20};
trans = dataArray{:, 21};
sstemp2 = dataArray{:, 22};


