function [Flow1,VarName8] = importfile(filename, startRow, endRow)
%IMPORTFILE Import numeric data from a text file as column vectors.
%   [FLOW1,VARNAME8] = IMPORTFILE(FILENAME) Reads data from text file
%   FILENAME for the default selection.
%
%   [FLOW1,VARNAME8] = IMPORTFILE(FILENAME, STARTROW, ENDROW) Reads data
%   from rows STARTROW through ENDROW of text file FILENAME.
%
% Example:
%   [Flow1,VarName8] = importfile('ACS_Flow_201025001.log',101, 101);
%
%    See also TEXTSCAN.

% Auto-generated by MATLAB on 2015/11/17 14:28:50

%% Initialize variables.
if nargin<=2
    startRow = 101;
    endRow = 101;
end

%% Format string for each line of text:
%   column7: text (%s)
%	column8: text (%s)
% For more information, see the TEXTSCAN documentation.
formatSpec = '%*33s%7s%1s%[^\n\r]';

%% Open the text file.
fileID = fopen(filename,'r');

%% Read columns of data according to format string.
% This call is based on the structure of the file used to generate this
% code. If an error occurs for a different file, try regenerating the code
% from the Import Tool.
dataArray = textscan(fileID, formatSpec, endRow(1)-startRow(1)+1, 'Delimiter', '', 'WhiteSpace', '', 'HeaderLines', startRow(1)-1, 'ReturnOnError', false);
for block=2:length(startRow)
    frewind(fileID);
    dataArrayBlock = textscan(fileID, formatSpec, endRow(block)-startRow(block)+1, 'Delimiter', '', 'WhiteSpace', '', 'HeaderLines', startRow(block)-1, 'ReturnOnError', false);
    for col=1:length(dataArray)
        dataArray{col} = [dataArray{col};dataArrayBlock{col}];
    end
end

%% Close the text file.
fclose(fileID);

%% Post processing for unimportable data.
% No unimportable data rules were applied during the import, so no post
% processing code is included. To generate code which works for
% unimportable data, select unimportable cells in a file and regenerate the
% script.

%% Allocate imported array to column variable names
Flow1 = dataArray{:, 1};
VarName8 = dataArray{:, 2};

