%% Import data from text file.
% Script for importing data from the following text file:
%
%    /Users/emmanuelboss/Desktop/NAAMES_data/Atlantis_underway/AT151xxx_0000.csv
%
% To extend the code to different selected data or a different text file,
% generate a function instead of a script.

% Auto-generated by MATLAB on 2015/11/16 19:10:52

%% Initialize variables.
filename = '/Users/emmanuelboss/Desktop/NAAMES_data/Atlantis_underway/AT151105_0000.csv';
delimiter = ',';
startRow = 3;
formatSpec = '%s%s%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%s%s%f%[^\n\r]';

%% Open the text file.
fileID = fopen(filename,'r');

%% Read columns of data according to format string.
dataArray = textscan(fileID, formatSpec, 'Delimiter', delimiter, 'EmptyValue' ,NaN,'HeaderLines' ,startRow-1, 'ReturnOnError', false);

%% Close the text file.
fclose(fileID);
%% Allocate imported array to column variable names
DATE_GMT = dataArray{:, 1};
TIME_GMT = dataArray{:, 2};
Dec_LAT = dataArray{:, 3};
Dec_LON = dataArray{:, 4};
SPD = dataArray{:, 5};
HDT = dataArray{:, 6};
COG = dataArray{:, 7};
SOG = dataArray{:, 8};
WXTP_Ta = dataArray{:, 9};
WXTS_Ta = dataArray{:, 10};
WXTP_Pa = dataArray{:, 11};
WXTS_Pa = dataArray{:, 12};
WXTP_Ri = dataArray{:, 13};
WXTS_Ri = dataArray{:, 14};
WXTP_Rc = dataArray{:, 15};
WXTS_Rc = dataArray{:, 16};
WXTP_Dm = dataArray{:, 17};
WXTS_Dm = dataArray{:, 18};
WXTP_Sm = dataArray{:, 19};
WXTS_Sm = dataArray{:, 20};
WXTP_Ua = dataArray{:, 21};
WXTS_Ua = dataArray{:, 22};
WXTP_TS = dataArray{:, 23};
WXTS_TS = dataArray{:, 24};
WXTP_TD = dataArray{:, 25};
WXTS_TD = dataArray{:, 26};
SWR = dataArray{:, 27};
LWR = dataArray{:, 28};
SBE45S = dataArray{:, 29};
SBE48T = dataArray{:, 30};
BAROM_P = dataArray{:, 31};
BAROM_S = dataArray{:, 32};
FLR = dataArray{:, 33};
SSVdslog = dataArray{:, 34};
Depth12 = dataArray{:, 35};
Depth35 = dataArray{:, 36};
EM122 = dataArray{:, 37};

%% Clear temporary variables
clearvars filename delimiter startRow formatSpec fileID dataArray ans;

A=datenum(cell2mat(DATE_GMT));
B=datenum(cell2mat(TIME_GMT))-floor(datenum(cell2mat(TIME_GMT)));
Matlab_time=A+B;
%Dec_LAT 
%Dec_LON 
%SBE45S 
%SBE48T 
%FLR 
day=A(1)-datenum('2015,1,1')+1; %compute yearday
hdr_out=['matlab_time'; 'Dec_LAT    '; 'Dec_Lon    '; 'salinity   '; 'temperature';'FL_chl     '];
data_out=[Matlab_time,Dec_LAT,Dec_LON,SBE45S,SBE48T,FLR];
file_name_out=['/Users/emmanuelboss/Desktop/NAAMES_data/Atlantis_underway/','Atlantis_underway_',num2str(day),'.dat'];
fprintf('\nwriting to file: %s\n',file_name_out);
wrtmerg(file_name_out,data_out',hdr_out);
fprintf('done\n');